# you need to run $ vagrant plugin install vagrant disksize

$installPackages = <<-SCRIPT
	sudo apt-get update 
	sudo apt-get -y upgrade 
	sudo apt-get -y install docker.io
	# libX11.so is needed by vivado post install scripts
	sudo apt-get -y install xserver-xorg-core --no-install-recommends --no-install-suggests
SCRIPT

$installVivado = <<-SCRIPT
	sudo apt-get -y install libncurses5
	sudo apt-get -y install libncurses5-dev libncursesw5-dev
	DISPLAY="" sudo /vagrant/Xilinx_Vivado_SDK_2018.2_0614_1954/xsetup \
		-a XilinxEULA,3rdPartyEULA,WebTalkTerms \
		-b Install -e "Vivado HL Design Edition" -l /opt/Xilinx	
SCRIPT

def failIfXilinxInstallDirNonExistent
	if ! Dir.exists?("./Xilinx_Vivado_SDK_2018.2_0614_1954") then
		print("Error: Xilinx Vivado 2018.2 installation dir is missing.\n")
		print("You must unpack Xilinx vivado to Xilinx_Vivado_SDK_2018.2_0614_1954\n")
		print("into the directory where this Vagrantfile resides in.\n")
		exit (1)	
	end
	return 0
end

Vagrant.configure("2") do |config|
	failIfXilinxInstallDirNonExistent()

	config.vm.box = "bento/ubuntu-20.04"

	config.vm.provider "virtualbox" do |v|
		v.memory = 1024*64
		v.cpus = 20
	end

	config.disksize.size = '100GB'

	config.vm.provision "shell", inline: $installPackages, privileged: false
	config.vm.provision "shell", inline: "sudo adduser vagrant docker", privileged: false
	config.vm.provision "shell", inline: $installVivado, privileged: false
end
